# Use a imagem oficial do Redis como base
FROM redis:latest

# Copie um arquivo de configuração personalizado (opcional)
# COPY redis.conf /usr/local/etc/redis/redis.conf

# Comando padrão para iniciar o Redis
# Use o arquivo de configuração se foi adicionado acima
CMD ["redis-server"]
